#!/bin/bash

set -eE
trap 'echo Error: in $0 on line $LINENO' ERR


attach_MOUNTPOINT() {
    local MOUNTPOINT="$1"

    if [ ! -c /dev/mem ]; then
        mknod -m 660 /dev/mem c 1 1
        chown root:kmem /dev/mem
    fi

    mount dev-live -t devtmpfs "$MOUNTPOINT/dev"
    mount devpts-live -t devpts -o nodev,nosuid "$MOUNTPOINT/dev/pts"
    mount proc-live -t proc "$MOUNTPOINT/proc"
    mount sysfs-live -t sysfs "$MOUNTPOINT/sys"
    mount securityfs -t securityfs "$MOUNTPOINT/sys/kernel/security"

    mount -t cgroup2 none "$MOUNTPOINT/sys/fs/cgroup"
    mount -t tmpfs none "$MOUNTPOINT/tmp"
    mount -t tmpfs none "$MOUNTPOINT/var/lib/apt/lists"
    mount -t tmpfs none "$MOUNTPOINT/var/cache/apt"
}

detach_MOUNTPOINT() {
    # Reverse the operations from setup_MOUNTPOINT
    local MOUNTPOINT
    MOUNTPOINT=$(realpath "$1")

    # ensure we have exactly one trailing slash, and escape all slashes for awk
    MOUNTPOINT_match=$(echo "$MOUNTPOINT" | sed -e's,/$,,; s,/,\\/,g;')'\/'
    # sort -r ensures that deeper MOUNTPOINTs are unmounted first
    awk </proc/self/mounts "\$2 ~ /$MOUNTPOINT_match/ { print \$2 }" | LC_ALL=C sort -r | while IFS= read -r submount; do
        mount --make-private "$submount"
        umount "$submount"
    done
}


export UBUNTU_RELASE_NAME="Ubuntu 24.10 (Oracular Oriole)"
export UBUNTU_RELASE_VERSION="24.10"

export PROJECT=ubuntu-cpc
export SUITE=oracular
export FLAVOR=server

export ARCH=arm64
export IMAGEFORMAT=none
export IMAGE_TARGETS=none

export DEBIAN_FRONTEND=noninteractive
export DEBCONF_NONINTERACTIVE_SEEN=true
export LC_ALL=C
export LC_CTYPE=C
export LANGUAGE=C
export LANG=C

export SYSROOT="xX__AARCH64__Xx"


set -x

# Create a SYSROOT directory and populate it with debootstrap.
debootstrap      \
    --arch=$ARCH \
    --components=main,universe,multiverse,restricted   \
    --include=$(python3 ./ruler/package.py --separator "," --server-essential-package-array) \
    oracular \
    $SYSROOT \
    "http://kambing.uu.sg/ubuntu-ports"
    # "http://ports.ubuntu.com/ubuntu-ports"


    # --extra-suites=oracular-updates,oracular-backports causing some serious issues.


# Apply HOSTNAME
echo "ubuntu" > $SYSROOT/etc/hostname

# Apply my package repo
cat > $SYSROOT/etc/apt/sources.list.d/nobara.sources << HEREDOC
Types: deb
URIs: http://dummy.nobara.in/ubuntu/
Suites: oracular
Components: nobara
Architectures: arm64
Trusted: yes
By-Hash: no
Signed-By: -----BEGIN PGP PUBLIC KEY BLOCK-----
 .
 mQENBGeDRlgBCADUrnMWBJlr4ZfSzdczAbwIcY4aCsai0TAQUTmAE4S41dlyYvie
 JvBSwbs3nvq9yLbSF4L68GeiFAX7U7e9MZiaD3D5HPx16jXFNCtnIxAhfRuKDZPq
 H/wsGJIECo9XA9sQjgvDqAcrwuBp0jpeLuwr0S/AZUsmoVPzvcDWOprKvlMxK46Q
 Ppi6vE2CpLnrg111JQMrud+BYuKqfvuNkJCy00v5fUD2LNZrDkUdlPKj0nkzAT5L
 8V5jCR36PhTMpu//64efK5D9JmVLoYk8Er5ouSYRDm1CF9m1Zc/to3j+uRD9gGjw
 EiMEWJ+acFOeRY/8wOHn+uXeUarSdVOV1UpHABEBAAG0IU5vYmFyYSBLdXJva2F3
 YSA8bm9iYXJhQGt1cm9rYXdhPokBUQQTAQgAOxYhBFlwN8eZ/zGMTVtQ/80LEULO
 9FO9BQJng0ZYAhsDBQsJCAcCAiICBhUKCQgLAgQWAgMBAh4HAheAAAoJEM0LEULO
 9FO952UH/2EkReyS2WpTRFakefO72fp/abzf5CIKXtLtXIM5sH2GvFpvRYldp0Dw
 DXTZvpfbFMZbWsu1GjyKI1tD2qnRwDUDPOMCJk/jgawaXi74I1my5MDx+SbmbHCz
 Q7ZgcwuUmDP4ad3JvpqTVMDJr2JDvLDxTzl5DySoYL8U6Jk/cNiYRMWXH9YEn91o
 YMmcYyGd/34bqUFcwPmNk6F0hnoCaErlthmTwHBrIrRhU9X3+VbSFKb1tSWDIST2
 w5DEHNFAzAH2jE/YnMFXIrPHYzQbLz3ZsXNqAqzGK10kl4Rkl5sjUk4rUDHRgYA4
 Tz7o/pLVaBTHpVovDqYVEshsGr77jsW5AQ0EZ4NGWAEIAMDVb1/5qsCm4Q/yXrUC
 k0c626aBQmyBVukv2M0E1sokO0XVnlslD7vy1PiiXi4wP1ijsNt4DQWpqMlReLt5
 JbKMdAB1BS9XpbpIHi5b4OzUO37UJAvMN4UA2sdut+7tGH34jf4oM9oFKfG4BANp
 6V3s12a16AjH6sjIA+sJBC5ckhv78KO9PWZL5i3a0+vlop52+DqbR2ydDxwwp4ao
 0tDWKYNemrzg/CWjVyPKKHL51SpZaJP/GjQc03n4uvFL4pgdJ8MW+D5KQvhRB3Aj
 /9zc8/gXO9R2CYbW2+D65/yq7Cmwv7CQuBlxIW36zsK1aM8WRzcaylYs/MnW2dhI
 Z8EAEQEAAYkBNgQYAQgAIBYhBFlwN8eZ/zGMTVtQ/80LEULO9FO9BQJng0ZYAhsM
 AAoJEM0LEULO9FO9n1UH/ipy/G3jGe2a/lNwNn04JladqYSE9loSrS93VRZZZ90p
 lv/TZClFVpoBu8yTAtd9tZ9pioEbjG5ki6uOe4dMDNdFlbZnLGDsY/mW65Mmu1ee
 zoum4V9nQz72AN/F7KVKMzJT/mrARVuoQJgG38XlfG50qkGki1y2OngW0KOnCT+4
 8I8btJ9LnTmnMT32r0PZFOKBMFTcQQBWlffrad8zJxz48J1jS9IkBtA1xdyhH5N/
 tbkb7NRvbU0F2GAov32QjqymS8P8jj7PybxkvOxzd9H3xweezz+oDbHUuUlvTLGh
 IPE3cSexDhwgDDqepGzMfo1ud7veeZezI/uB5PWIZI4=
 =IGL8
 -----END PGP PUBLIC KEY BLOCK-----
HEREDOC


# Attach SYSROOT.
attach_MOUNTPOINT $SYSROOT

# Update, Upgrade, Add repositories.
chroot $SYSROOT apt update
chroot $SYSROOT apt -y upgrade
chroot $SYSROOT apt -y dist-upgrade
chroot $SYSROOT add-apt-repository -y ppa:jjriek/rockchip          # We need Joshua's repo.
chroot $SYSROOT add-apt-repository -y ppa:oibaf/graphics-drivers   # We need the upstream mesa repo.
chroot $SYSROOT apt update
chroot $SYSROOT apt -y --no-install-recommends install ubuntu-server-rockchip u-boot-orangepi-5-plus u-boot-tools u-boot-menu \
                                                       $(python3 ./ruler/package.py --separator " " --oibaf-gpu-packages --pipewire-server-packages)
                                                       # This would install a bunch of packages.

# chroot $SYSROOT apt -y --no-install-recommends install kernel-6.13.0-opi5plus # Should pull my kernel build as the repo was added previously.
chroot $SYSROOT apt -y upgrade


#### Here Be Monkeys ####
patch --strip=1 --directory=$SYSROOT < patcher/ubuntu/server-1.patch


#### Probably don't need this in here ####
# chroot $SYSROOT update-initramfs -u

# Get everything clean.
chroot $SYSROOT apt -y autoremove
chroot $SYSROOT apt autoclean
chroot $SYSROOT apt clean


# Generate ssh keys.
chroot $SYSROOT ssh-keygen -A

#### We should be done by now ####
# Detach SYSROOT.
detach_MOUNTPOINT $SYSROOT

# Package SYSROOT.
(cd $SYSROOT &&  tar -p -c --sort=name --xattrs ./*) | xz -3 -T0 > "ubuntu-${UBUNTU_RELASE_VERSION}-preinstalled-${FLAVOR}-arm64.rootfs.tar.xz"

# Delete the SYSROOT directory
# rm -rf $SYSROOT

set +x

echo "Bye Bye!!"

trap '' EXIT
exit 0
