# This is a basic workflow to help you get started with Actions

name: TRIAL

# Controls when the workflow will run
on:
    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    # This workflow contains a single job called "kernel-build"
    kernel-release:
        # The type of runner that the job will run on
        runs-on: ubuntu-24.04
        outputs:

        # Steps represent a sequence of tasks that will be executed as part of the job
        steps:
            # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
            - uses: actions/checkout@v4

            - name: Trying out.
              run: |
                mkdir -p package-0.1_0.1.0~r5-1102_arm64/DEBIAN
                echo "Package: package-0.1" >> package-0.1_0.1.0~r5-1102_arm64/DEBIAN/control
                echo "Version: 0.1.0~r5-1102" >> package-0.1_0.1.0~r5-1102_arm64/DEBIAN/control
                dpkg-deb --compression=gzip --build package-0.1_0.1.0~r5-1102_arm64 package-0.1_0.1.0~r5-1102_arm64_gzip.deb
                dpkg-deb --compression=xz --build package-0.1_0.1.0~r5-1102_arm64 package-0.1_0.1.0~r5-1102_arm64_xz.deb

            - name: Upload package
              uses: actions/upload-artifact@v4.5.0
              with:
                name: package
                path: "*.deb"
                compression-level: 0
                if-no-files-found: error


