# This is a basic workflow to help you get started with Actions

name: BUILD-UBUNTU

# Controls when the workflow will run
on:
    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    # This workflow contains a single job called "kernel-build"
    build-sysroot:
        # The type of runner that the job will run on
        runs-on: ubuntu-24.04

        # Steps represent a sequence of tasks that will be executed as part of the job
        steps:
            # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
            - uses: actions/checkout@v4

            - name: Build a Ubuntu server system and image.
              run: |
                sudo ./minimal-system.sh
                sodo ./minimal-image.sh

              shell: bash

            - name: Upload ubuntu image.
              uses: actions/upload-artifact@v4.5.0
              with:
                name: ubuntu.rootfs
                path: ./ubuntu*.img
                compression-level: 0
                if-no-files-found: error
