# This is a basic workflow to help you get started with Actions

name: BUILD-UBUNTU

# Controls when the workflow will run
on:
    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    # This workflow contains a single job called "kernel-build"
    build-ubuntu:
        # The type of runner that the job will run on
        runs-on: ubuntu-24.04

        # Steps represent a sequence of tasks that will be executed as part of the job
        steps:
            # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
            - uses: actions/checkout@v4

            - name: Install dependencies.
              run: |
                sudo apt update
                sudo apt upgrade -y
                sudo apt install -y qemu-user-static qemu-system-arm qemu-efi-aarch64 u-boot-tools
                # sudo apt install -y build-essential gcc-aarch64-linux-gnu bison  devscripts        \
                # qemu-user-static qemu-system-arm qemu-efi-aarch64 u-boot-tools binfmt-support      \
                # debootstrap flex libssl-dev bc rsync kmod cpio xz-utils fakeroot parted            \
                # udev dosfstools uuid-runtime git-lfs device-tree-compiler python3 dctrl-tools      \
                # python-is-python3 fdisk bc debhelper python3-pyelftools python3-setuptools         \
                # python3-distutils-extra python3-pkg-resources swig libfdt-dev libpython3-dev dctrl-tools

            - name: Build a Ubuntu server system and image.
              run: |
                # sudo ./ruler/ubuntu
                gh run download --repo nobara256/ubuntu 12731539512
                mv ./ubuntu-image/*.tar.xz .
                sudo ./ruler/image

              shell: bash
              env:
                GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Upload ubuntu image.
              uses: actions/upload-artifact@v4.5.0
              with:
                name: ubuntu-image
                # path: ./ubuntu*.tar.xz
                path: ./ubuntu*.img.xz
                compression-level: 0
                if-no-files-found: error
